name: Build and publish VSIX release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  build-and-release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install base dependencies
        working-directory: ./
        run: |
          npm ci
          npm run download-api


      - name: Install webview dependencies
        working-directory: ./webview-ui
        run: |
          npm ci

      - name: Bump patch version
        run: |
          npm version patch --no-git-tag-version

      - name: Build extension
        run: npm run compile:extension
        working-directory: ./

      - name: Build webview
        run: npm run compile
        working-directory: ./webview-ui

      - name: Commit and push version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: bump version for release"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF_NAME}
          fi

      - name: Package VS Code extension
        run: npx vsce package --out generic-copilot-providers.vsix

      - name: Get latest commit message
        id: commit
        run: |
          msg=$(git log -1 --pretty=%B | sed ':a;N;$!ba;s/"/'"'""'"'"/g')
          echo "message<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get version from package.json
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with VSIX asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          name: v${{ steps.pkg.outputs.version }}
          body: ${{ steps.commit.outputs.message }}
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
